services:
### Web Server: interface for users to interact with the application
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      args:
        OPENSSL_SUBJ: ${OPENSSL_SUBJ:?}
    environment:
        URL: ${URL:?}
    networks:
      - public-network
    ports:
      - "4443:443"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsk https://localhost/ | grep -q . || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    restart: always

networks:
  public-network:
    driver: bridge
    external: true
