services:

### Web Server: interface for users to interact with the application
  nginx:
    container_name: nginx
    build: 
      context: ./nginx
      args:
        OPENSSL_SUBJ: ${OPENSSL_SUBJ:?}
    environment:
        URL: ${URL:?}
    ports:
      - "4443:443"
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "curl -fsk https://localhost/ | grep -q . || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    environment:
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - default

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.0
    ports:
      - "5601:5601"
    networks:
      - default

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:8.13.0
    user: root
    networks:
      - default
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

networks:
  default:
    driver: bridge

volumes:
  esdata:
    driver: local
