services:
# Web server : only access from outside
  nginx:
    container_name: nginx
    build: 
      context: ./requirements/nginx
      args:
        OPENSSL_SUBJ: ${OPENSSL_SUBJ:?}
    environment:
        URL: ${URL:?}
    networks:
      - basic-network
    ports:
      - "443:443"
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -fsk https://localhost/ | grep -q . || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    restart: always

# Relational Database (RDBMS)
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - basic-network
    volumes:
      - volume-db:/database
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:?}
      MYSQL_USER: ${MYSQL_USER:?}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      start_period: 5s
      retries: 10
    restart: always

volumes:
  volume-db: #database : mariadb
    name: "db"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "${HOST_DATA_PATH}/data/db"

networks:
  basic-network: # Accessible only by ports from nginx
    driver: bridge
    internal: false
